package example;

@Stream
declare Person
    @TableColumn("name")
    name : String
    @TableColumn("date")
    dateOfBirth : java.util.Date
    @TableColumn("phone")
    phone : Int
    @TableColumn("hight")
    hight : Int
    isTall : Boolean
end

rule "rule one"
    when
        $p : Person( (name == "Jimmy" && hight > 150) || (hight < 120 && name == "carry") , isTall == true)
    then
        System.out.println("rule one starting ----------------------------------");
        System.out.println("this is " + $p.getName());
        System.out.println("complex condition pass");
        $p.setName("sally");
        System.out.println("rule one finishing ---------------------------------");
        //thisrule.stopThisOne();
end

