package example;
import java.util.HashMap;

declare Type
    t1 : Long
    t2 : Short
    t3 : Double
    t4 : Byte
    t5 : Date
    t6 : Time
    t7 : Timestamp
    t8 : String
    t9 : Int
    t10: Float
    t11: Character
    t12: Boolean
    t13: Integer
    t14: BigDecimal
    t15: Json
end

global
    HashMap map = new HashMap();
end

rule "test all type"
    when
        $t : Type(t1 == 1, t2 == 2, t3 == 3.0, t4 == "4", t5 == "Thu Nov 01 18:27:06 CST 2018",
                  t6 == "06:06:06", t7 == "1970-07-07 07:07:07", t8 == "8", t9 == 9, t10 == 10.0, t11 == "c", t12 == false,
                  t13 == 13, t14 == 14, t15.a.b <= 15)
    then
        $t.setT12(true);
        map.put("nice", "sally");
        if (map.size() == 1) {
            System.out.println("I am two");
        }
end