package example;

import datasource persons;

@Stream
declare Person2
    @TableColumn("name")
    name : String
    @TableColumn("age")
    age : Int
    @TableColumn("gender")
    gender : Boolean
    @TableColumn("json")
    json : Json
end

@Table("test")
declare Test
    @DatasourceColumn(id = true, key = true, column = "id")
    id : String
    @DatasourceColumn(id = false, key = true, column = "age")
    age : Int
end

rule "rule one"
    when
        $p : Person2( (name == "Jimmy" && age < 15) || (age > 15 && name == "carry") , gender == true)
        $l : Test( age < $p.getAge ) from persons
    then
        System.out.println("rule one starting ----------------------------------");
        System.out.println("this is " + $p.getName());
        System.out.println("complex condition pass");
        System.out.println("smaller age is " + $l.get(0).getAge());
        System.out.println("rule one finishing ---------------------------------");
        //thisrule.stopThisOne();
end

